### ISSUE TITLE
Add Freezing World If Nobody is in that world

### ISSUE THREAD

**Issue by Cyberillc** [Malfrador/FreezeHibernate#1]
Adding that would significantly reduce CPU usage.

**Comment by Malfrador** [comment]
The tick rate is always for the entire server. Having worlds tick at different rates (or not at all) is not something the game supports, so this can't be done without modifying the server software itself.

All I can recommend would be disabling spawn chunks in each world - that way there is nothing there to tick when no players are in the world (`/gamerule spawnChunkRadius 0`). That should have pretty much the same effect.
